= Spring JAX-RS Client Proxy
Jakub Narloch <j.narloch@gmail.com>
:toc: left
:sectnums:

A easy to use utility that registers your JAX-RS clients based on the service interfaces

Currently supports: CXF, RESTEasy, Jersey

== Introduction

The JAX-RS 1.1/2.0 is well establish standard, although the fully programmatic approach for coding the service clients
requires a lot of boilerplate code. An alternative is to use the proxy client generation based on the service contract
(i.e. annotated service interface) this still has it's pitfalls and has different level of support across the frameworks
although it can speed up the development and it is really easy to setup.

Currently there is no out of the box support for registering the service proxy clients within the Spring's application
context, so this little utility project tries to fill this gap.

=== Setting up

The registration of the client beans is straightforward and requires only to point the location to JAX-RS annotated
interfaces by adding the EnableJaxRsClient annotation to you annotated configuration class.

[source, java]
----

@EnableJaxRsClient(
    basePackages = "com.app.rest.api",
    serviceUrl = "localhost:8080/api"
)
@Configuration
public class AppConfig {

}

----

=== SpEL url resolution

The `EnableJaxRsClient.serviceUrl` in fact accepts and evaluates any valid SpEL expressions, so it might be more
convenient to resolve that against configured property source as fallows:

[source, java]
----
@PropertySources(
        @PropertySource("classpath:config/app.properties")
)
@EnableJaxRsClient(
    basePackages = "com.app.rest.api",
    serviceUrl = "#{environment['rest.api.service.url']}"
)
@Configuration
public class AppConfig {

}

----

=== Specifying the service url

In real world situations it might be more convenient to read the url from external configuration at runtime or
customize the logic in any other manner. In order to do this `serviceUrl` can be omitted, in such situations
library tries to lookup `ServiceUrlProvider` instance from the application context and use that for acquiring
the remote service url.

[source, java]
----

@Configuration
public class AppConfig {

    @Bean
    public ServiceUrlProvider urlProvider() {
        return new ServiceUrlProvider() {
            @Override
            public String getServiceUrl() {
                // ... obtain the url
            }
        };
    }
}

----

=== Enabling client proxy generation

The proxy classes are in fact being generated by specific JAX-RS provider (like CXF or RESTEasy) and in order to enable
those you have to add one of the fallowing annotations.

[cols="2*", options="header"]
|===
| Library | Annotation
| CXF | @EnableCxfClient
| RESTEasy | @EnableRestEasyClient
| Jersey | @EnableJerseyClient

|===

=== Additional configuration

It is possible to customize the JAX-RS client by registering additional provider classes. The `JaxRsClientConfigurer`
provides additional methods for customization.

[source, java]
----

@EnableJaxRsClient(
    basePackages = "com.app.rest.api",
    serviceUrl = "localhost:8080/api"
)
@EnableRestEasyClient
@Configuration
public class AppConfig implements JaxRsClientConfigurer {

    @Override
    public void registerProviders(ProviderRegistry providerRegistry) {

        providerRegistry
                .addProvider(GZIPEncodingInterceptor.class)
                .addProvider(GZIPDecodingInterceptor.class);
    }
}

----

Note: The providers might be framework specific.